<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/marx.min.css')
            ->prependStylesheet($this->basePath() . '/css/style.css'); ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js'); ?>

    </head>
    <body>
        <main>
            <h1></h1>            
        </main>
    </body>
</html>
